version: '3.9'
services:
  api:
    build:
      context: api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
  nginx:
    image: nginx
    # in docker-compose, paths are relative to the docker-compose file
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ${CERT}
      - ${KEY}
    ports:
      - "80:80"
      - "443:443"
    # specify that the flask_api container must be running before the nginx container
    depends_on:
<<<<<<< HEAD
      - kickoff_app
      - react-app
      - mongo
=======
      - api
      - frontend
>>>>>>> 0d3054911165025f20a38aaa44f6d10db645f4f5
    # specify that logging should be managed in a rotating basis
    logging:
      driver: "local"
      options:
        max-size: "10m"
<<<<<<< HEAD
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  
=======
>>>>>>> 0d3054911165025f20a38aaa44f6d10db645f4f5
