name: Deploy

on:
  push:
    branches:
      - main

jobs:
  Deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 
      - name: SSH into EC2 Instance
        env:
          HOSTNAME: ${{ secrets.TEST_EC2_PUBLIC_IP }}
          USER_NAME: ${{ secrets.USER_NAME }}
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -T -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME}
          cd Mirrulations_Search/
          sudo docker-compose down
          git pull
          sudo docker-compose build
          sudo docker-compose up -d
